Allow to load/store root owned directories via action; add slug(local-dir) based namespacing to the remote storage directory
Pull Request: https://github.com/dimikot/ci-storage/pull/23 (main)

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -8,31 +8,31 @@ inputs:
     description: "What to do (store or load)."
     required: true
   storage-host:
-    description: "Storage host in the format [user@]host[:port]; it must allow password-free SSH key based access. If not passed, tries to read it from ~/ci-storage-host file."
+    description: "Storage host in the format [user@]host[:port]; it must allow password-free SSH key based access. Default: the content of ~/ci-storage-host file."
     required: false
   storage-dir:
-    description: "Storage directory on the remote host. If not set, uses /mnt. Notice that owner and repo are always appended, so the final directory will be {storage-dir}/{owner}/{repo} or {storage-dir}/{owner}/{repo}.{storage-namespace}."
+    description: "Storage directory on the remote host. Notice that, when building the final directory on the storage host, owner and repo are always appended, so the path will be {storage-dir}/{owner}/{repo}/{slug(local-dir)} or {storage-dir}/{owner}/{repo}/{slug(local-dir)}.{layer-name}. Default: /mnt"
     required: false
   storage-max-age-sec:
-    description: "Remove slots created earlier than this many seconds ago. If not set, uses the ci-storage tool default 4 hours."
+    description: "Remove slots created earlier than this many seconds ago. Default: 14400 (4 hours)."
     required: false
   slot-id:
-    description: 'Id of the slot to store to or load from; use "*" to load a smart-random slot (e.g. most recent or best in terms of layer compatibility) and skip if it does not exist. If empty, uses $GITHUB_RUN_ID value (which is friendly to "Re-run failed jobs").'
+    description: 'Id of the slot to store to or load from; use "*" to load a smart-random slot (e.g. most recent or best in terms of layer compatibility) and skip if it does not exist. Default: $GITHUB_RUN_ID (which is friendly to "Re-run failed jobs").'
     required: false
   local-dir:
-    description: 'Local directory path to store from or load to. If not set, uses "." (the current work directory).'
+    description: 'Local directory path to store from or load to. The value namespaces the data stored, so different local-dir values correspond to different storages. If the owner of the directory is different from the current user, then ci-storage tool is run with sudo, and the binary is used not from the action directory, but from /usr/bin/ci-storage. Default: "." (current work directory).'
     required: false
   exclude:
-    description: "Newline separated exclude pattern(s) for rsync."
+    description: "Newline separated exclude pattern(s) for rsync. Default: empty."
     required: false
   layer-name:
-    description: "If set, the final directory on the storage host will be {storage-dir}/{owner}/{repo}.{layer-name}, plus deletion will be turned off on load."
+    description: "If set, the final directory on the storage host will be {storage-dir}/{owner}/{repo}/{slug(local-dir)}.{layer-name}, plus deletion will be turned off on load. Default: empty."
     required: false
   layer-include:
-    description: "Newline-separated include pattern(s) for rsync. If set, only the files matching the patterns will be transferred. Implies setting layer-name."
+    description: "Newline-separated include pattern(s) for rsync. If set, only the files matching the patterns will be transferred. Implies setting layer-name. Default: empty."
     required: false
   verbose:
-    description: "If set, prints the list of transferred files."
+    description: "If set, prints the list of transferred files. Default: false."
     required: false
 runs:
   using: "composite"
@@ -68,22 +68,39 @@ runs:
           slot_id="$default_run_hash $slot_id"
         fi
 
+        if [[ "$local_dir" == "/" ]]; then
+          echo "You cannot use / as local-dir."
+          exit 1
+        elif [[ "$local_dir" == "." ]]; then
+          storage_dir="$storage_dir/_"
+        else
+          storage_dir="$storage_dir/$(echo "$local_dir" | tr / _)"
+        fi
+
         if [[ "$layer_name" != "" ]]; then
           layer_include=${layer_include:-"*"}
           storage_dir="$storage_dir.$layer_name"
         fi
+
         if [[ "$layer_include" != "" && "$layer_name" == "" ]]; then
           echo "When layer-include is used, you must also pass layer-name."
           exit 1
         fi
 
-        "${{ github.action_path }}/ci-storage" \
-          --storage-host="$storage_host" \
-          --storage-dir="$storage_dir" \
-          --storage-max-age-sec="$storage_max_age_sec" \
-          --slot-id="$slot_id" \
-          --local-dir="$local_dir" \
-          --exclude="$exclude" \
-          --layer="$layer_include" \
-          $verbose \
+        args=(
+          --storage-host="$storage_host"
+          --storage-dir="$storage_dir"
+          --storage-max-age-sec="$storage_max_age_sec"
+          --slot-id="$slot_id"
+          --local-dir="$local_dir"
+          --exclude="$exclude"
+          --layer="$layer_include"
+          $verbose
           "$action"
+        )
+
+        if [[ -d "$local_dir" && "$(stat -c '%U' "$local_dir")" != "$(whoami)" ]]; then
+          sudo /usr/bin/ci-storage "${args[@]}"
+        else
+          "${{ github.action_path }}/ci-storage" "${args[@]}"
+        fi
